/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remena_nena.pantalles;

import remena_nena.Interficie.FinestraCondicio;
import remena_nena.Interficie.FinestraInicial;

/**
 *
 * @author pere
 */
public class fixarCondicio extends javax.swing.JFrame {

    FinestraCondicio finCon;

    /**
     * Creates new form fixarCondicio
     */
    public fixarCondicio(FinestraCondicio f) {
        finCon = f;
        initComponents();
        groupCond.add(relativaRadio);
        groupCond.add(absolutaRadio);
        relativaPanel.setVisible(false);
        absolutaPanel.setVisible(false);
        etapesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finCon.getEtapes();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        etapesList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finCon.getEtapes();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCond = new javax.swing.ButtonGroup();
        relativaRadio = new javax.swing.JRadioButton();
        absolutaRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        dacord = new javax.swing.JButton();
        relativaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        etapesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        accionsList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        memesList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        clicsField = new javax.swing.JTextField();
        absolutaPanel = new javax.swing.JPanel();
        jScrollList = new javax.swing.JScrollPane();
        etapesList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        accionsList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relativaRadio.setText("Relativa");
        relativaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relativaRadioActionPerformed(evt);
            }
        });

        absolutaRadio.setText("Absoluta");
        absolutaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absolutaRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipus de condició: ");

        exit.setText("Cancel·la");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        dacord.setText("D'acord");
        dacord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dacordActionPerformed(evt);
            }
        });

        relativaPanel.setPreferredSize(new java.awt.Dimension(537, 472));

        etapesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etapesListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(etapesList);

        jLabel2.setText("Selecciona una etapa:");

        jLabel3.setText("Selecciona una acció:");

        accionsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accionsListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(accionsList);

        jLabel4.setText("Selecciona un meme:");

        memesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memesListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(memesList);

        javax.swing.GroupLayout relativaPanelLayout = new javax.swing.GroupLayout(relativaPanel);
        relativaPanel.setLayout(relativaPanelLayout);
        relativaPanelLayout.setHorizontalGroup(
            relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relativaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        relativaPanelLayout.setVerticalGroup(
            relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relativaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relativaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(relativaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relativaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relativaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel5.setText("Nombre de clics:");

        absolutaPanel.setPreferredSize(new java.awt.Dimension(537, 472));

        etapesList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etapesList1MouseClicked(evt);
            }
        });
        jScrollList.setViewportView(etapesList1);

        jLabel6.setText("Selecciona una etapa:");

        jLabel7.setText("Selecciona una acció:");

        accionsList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accionsList1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(accionsList1);

        javax.swing.GroupLayout absolutaPanelLayout = new javax.swing.GroupLayout(absolutaPanel);
        absolutaPanel.setLayout(absolutaPanelLayout);
        absolutaPanelLayout.setHorizontalGroup(
            absolutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absolutaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(absolutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(absolutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        absolutaPanelLayout.setVerticalGroup(
            absolutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absolutaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(absolutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(absolutaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(absolutaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relativaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dacord)
                        .addGap(18, 18, 18)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(relativaRadio)
                                .addGap(18, 18, 18)
                                .addComponent(absolutaRadio))
                            .addComponent(clicsField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(absolutaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relativaRadio)
                    .addComponent(absolutaRadio)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clicsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relativaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dacord)
                    .addComponent(exit))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(absolutaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dacordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dacordActionPerformed
        boolean isInt;
        int clics = -1;
        try {
            clics = Integer.parseInt(clicsField.getText());
            isInt = true;
        } catch (NumberFormatException e) {
            isInt = false;
        }
        if (isInt && clics > 0) {
            finCon.setClicsCondicio(clics);
            if (relativaRadio.isSelected() && !etapesList.isSelectionEmpty() && !accionsList.isSelectionEmpty()
                && !memesList.isSelectionEmpty()) {
                finCon.setEtapaActiva(etapesList.getSelectedValue());
                int accio = Integer.parseInt(accionsList.getSelectedValue());
                finCon.setIdAccio(accio);
                finCon.setIdMeme(memesList.getSelectedValue());
                finCon.acceptarRelativa();
                this.setVisible(false);
                FinestraInicial p = new FinestraInicial(finCon.getK());
                Inicial ini = new Inicial(p);
                ini.setVisible(true);
            } else if (absolutaRadio.isSelected() && !etapesList1.isSelectionEmpty() && !accionsList1.isSelectionEmpty()) {
                finCon.setEtapaActiva(etapesList1.getSelectedValue());
                int accio = Integer.parseInt(accionsList1.getSelectedValue());  
                finCon.setIdAccio(accio);
                finCon.acceptarAbsoluta();
                this.setVisible(false);
                FinestraInicial p = new FinestraInicial(finCon.getK());
                Inicial ini = new Inicial(p);
                ini.setVisible(true);
            }
        }
    }//GEN-LAST:event_dacordActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        FinestraInicial p = new FinestraInicial(finCon.getK());
        Inicial ini = new Inicial(p);
        ini.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void etapesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etapesListMouseClicked
        String e = etapesList.getSelectedValue();
        finCon.setEtapaActiva(e);
        accionsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finCon.getAccions();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        memesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finCon.getLlistaMemes();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }//GEN-LAST:event_etapesListMouseClicked

    private void accionsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accionsListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accionsListMouseClicked

    private void memesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memesListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_memesListMouseClicked

    private void relativaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relativaRadioActionPerformed
        absolutaPanel.setVisible(false);
        relativaPanel.setVisible(true);
    }//GEN-LAST:event_relativaRadioActionPerformed

    private void etapesList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etapesList1MouseClicked
        String e = etapesList1.getSelectedValue();
        finCon.setEtapaActiva(e);
        accionsList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finCon.getAccions();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });

        
    }//GEN-LAST:event_etapesList1MouseClicked

    private void accionsList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accionsList1MouseClicked



    }//GEN-LAST:event_accionsList1MouseClicked

    private void absolutaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absolutaRadioActionPerformed
        relativaPanel.setVisible(false);
        absolutaPanel.setVisible(true);    }//GEN-LAST:event_absolutaRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fixarCondicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fixarCondicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fixarCondicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fixarCondicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absolutaPanel;
    private javax.swing.JRadioButton absolutaRadio;
    private javax.swing.JList<String> accionsList;
    private javax.swing.JList<String> accionsList1;
    private javax.swing.JTextField clicsField;
    private javax.swing.JButton dacord;
    private javax.swing.JList<String> etapesList;
    private javax.swing.JList<String> etapesList1;
    private javax.swing.JButton exit;
    private javax.swing.ButtonGroup groupCond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> memesList;
    private javax.swing.JPanel relativaPanel;
    private javax.swing.JRadioButton relativaRadio;
    // End of variables declaration//GEN-END:variables
}
