/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remena_nena.pantalles;

import remena_nena.Interficie.FinestraEncadenament;
import remena_nena.Interficie.FinestraInicial;
import remena_nena.Interficie.FinestraSelecEncadenament;

/**
 *
 * @author pere
 */
public class SelecEncadenament extends javax.swing.JFrame {

    FinestraSelecEncadenament finSel;

    /**
     * Creates new form SelecEncadenament
     */
    public SelecEncadenament(FinestraSelecEncadenament f) {
        finSel = f;
        initComponents();
        this.setTitle(finSel.getNomCampanya());
        buttonGroup.add(radioSequencia);
        buttonGroup.add(radioFinal);
        buttonGroup.add(radioDisparador);
        etapesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = finSel.getEtapes();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        etapesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioFinal = new javax.swing.JRadioButton();
        radioSequencia = new javax.swing.JRadioButton();
        radioDisparador = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(450, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("D'acord");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jButton4.setText("Cancel·la");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        etapesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(etapesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 130));

        jLabel1.setText("Tipus d'encadenament:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setText("Selecciona una etapa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        radioFinal.setText("Final");
        radioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFinalActionPerformed(evt);
            }
        });
        getContentPane().add(radioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        radioSequencia.setText("Seqüència");
        getContentPane().add(radioSequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        radioDisparador.setText("Disparador");
        radioDisparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDisparadorActionPerformed(evt);
            }
        });
        getContentPane().add(radioDisparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!etapesList.isSelectionEmpty()) {
            finSel.setNomEtapa(etapesList.getSelectedValue());
            if (radioDisparador.isSelected()) {
                finSel.dacord();
                this.setVisible(false);
                FinestraEncadenament enc = new FinestraEncadenament(finSel.getControlador());
                AfegirDisparador finDisp = new AfegirDisparador(enc);
                finDisp.setVisible(true);
                
            } else if (radioFinal.isSelected()) {
                finSel.finalitzador();
                this.setVisible(false);
                FinestraInicial p = new FinestraInicial(finSel.getControlador());
                Inicial ini = new Inicial(p);
                ini.setVisible(true);
            } else if (radioSequencia.isSelected()) {
                finSel.dacord();
                this.setVisible(false);
                FinestraEncadenament enc = new FinestraEncadenament(finSel.getControlador());
                AfegirSeq finSeq = new AfegirSeq(enc);
                finSeq.setVisible(true);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        FinestraInicial p = new FinestraInicial(finSel.getControlador());
        Inicial ini = new Inicial(p);
        ini.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFinalActionPerformed

    private void radioDisparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDisparadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDisparadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecEncadenament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecEncadenament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecEncadenament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecEncadenament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JList<String> etapesList;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDisparador;
    private javax.swing.JRadioButton radioFinal;
    private javax.swing.JRadioButton radioSequencia;
    // End of variables declaration//GEN-END:variables
}
